apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "vol7" 
spec:
  capacity:
    storage: "2Gi" 
  accessModes:
    - "ReadWriteOnce"
  hostPath: 
    path: "/opt/data/vol7"
apiVersion: "v1"

