apiVersion: v1
kind: Service
metadata:
  name: jenkins-slave
  namespace: jke-for-vols
  selfLink: /api/v1/namespaces/jke-for-vols/services/jenkins-slave
  uid: 1c579749-eb8f-11e5-8b10-22000a7b8cdf
spec:
  selector:
    name: jenkins
  sessionAffinity: None
  ports:
  - nodePort: 0
    port: 5000               
    protocol: TCP
    targetPort: 5000
status:
  loadBalancer: {  }
